/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivioIndexRouteImport } from './routes/archivio.index'
import { Route as ArchivioOrdRouteImport } from './routes/archivio.$ord'
import { Route as RepartoRepartoRouteImport } from './routes/reparto.$reparto'
import { Route as SchedaIdRouteImport } from './routes/scheda.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivioIndexRoute = ArchivioIndexRouteImport.update({
  id: '/archivio/',
  path: '/archivio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivioOrdRoute = ArchivioOrdRouteImport.update({
  id: '/archivio/$ord',
  path: '/archivio/$ord',
  getParentRoute: () => rootRouteImport,
} as any)
const RepartoRepartoRoute = RepartoRepartoRouteImport.update({
  id: '/reparto/$reparto',
  path: '/reparto/$reparto',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedaIdRoute = SchedaIdRouteImport.update({
  id: '/scheda/$id',
  path: '/scheda/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archivio/$ord': typeof ArchivioOrdRoute
  '/reparto/$reparto': typeof RepartoRepartoRoute
  '/scheda/$id': typeof SchedaIdRoute
  '/archivio/': typeof ArchivioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archivio/$ord': typeof ArchivioOrdRoute
  '/reparto/$reparto': typeof RepartoRepartoRoute
  '/scheda/$id': typeof SchedaIdRoute
  '/archivio': typeof ArchivioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archivio/$ord': typeof ArchivioOrdRoute
  '/reparto/$reparto': typeof RepartoRepartoRoute
  '/scheda/$id': typeof SchedaIdRoute
  '/archivio/': typeof ArchivioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/archivio/$ord' | '/reparto/$reparto' | '/scheda/$id' | '/archivio/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archivio/$ord' | '/reparto/$reparto' | '/scheda/$id' | '/archivio'
  id:
    | '__root__'
    | '/'
    | '/archivio/$ord'
    | '/reparto/$reparto'
    | '/scheda/$id'
    | '/archivio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivioOrdRoute: typeof ArchivioOrdRoute
  RepartoRepartoRoute: typeof RepartoRepartoRoute
  SchedaIdRoute: typeof SchedaIdRoute
  ArchivioIndexRoute: typeof ArchivioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivio/': {
      id: '/archivio/'
      path: '/archivio'
      fullPath: '/archivio/'
      preLoaderRoute: typeof ArchivioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivio/$ord': {
      id: '/archivio/$ord'
      path: '/archivio/$ord'
      fullPath: '/archivio/$ord'
      preLoaderRoute: typeof ArchivioOrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparto/$reparto': {
      id: '/reparto/$reparto'
      path: '/reparto/$reparto'
      fullPath: '/reparto/$reparto'
      preLoaderRoute: typeof RepartoRepartoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheda/$id': {
      id: '/scheda/$id'
      path: '/scheda/$id'
      fullPath: '/scheda/$id'
      preLoaderRoute: typeof SchedaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivioOrdRoute: ArchivioOrdRoute,
  RepartoRepartoRoute: RepartoRepartoRoute,
  SchedaIdRoute: SchedaIdRoute,
  ArchivioIndexRoute: ArchivioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
