/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivioRouteImport } from './routes/archivio'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchivioOrdRouteImport } from './routes/archivio.$ord'
import { Route as RepartoRepartoRouteImport } from './routes/reparto.$reparto'
import { Route as SchedaIdRouteImport } from './routes/scheda.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivioRoute = ArchivioRouteImport.update({
  id: '/archivio',
  path: '/archivio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivioOrdRoute = ArchivioOrdRouteImport.update({
  id: '/$ord',
  path: '/$ord',
  getParentRoute: () => ArchivioRoute,
} as any)
const RepartoRepartoRoute = RepartoRepartoRouteImport.update({
  id: '/reparto/$reparto',
  path: '/reparto/$reparto',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedaIdRoute = SchedaIdRouteImport.update({
  id: '/scheda/$id',
  path: '/scheda/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRouteWithChildren
  '/auth': typeof AuthRoute
  '/archivio/$ord': typeof ArchivioOrdRoute
  '/reparto/$reparto': typeof RepartoRepartoRoute
  '/scheda/$id': typeof SchedaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRouteWithChildren
  '/auth': typeof AuthRoute
  '/archivio/$ord': typeof ArchivioOrdRoute
  '/reparto/$reparto': typeof RepartoRepartoRoute
  '/scheda/$id': typeof SchedaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archivio': typeof ArchivioRouteWithChildren
  '/auth': typeof AuthRoute
  '/archivio/$ord': typeof ArchivioOrdRoute
  '/reparto/$reparto': typeof RepartoRepartoRoute
  '/scheda/$id': typeof SchedaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archivio'
    | '/auth'
    | '/archivio/$ord'
    | '/reparto/$reparto'
    | '/scheda/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archivio'
    | '/auth'
    | '/archivio/$ord'
    | '/reparto/$reparto'
    | '/scheda/$id'
  id:
    | '__root__'
    | '/'
    | '/archivio'
    | '/auth'
    | '/archivio/$ord'
    | '/reparto/$reparto'
    | '/scheda/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivioRoute: typeof ArchivioRouteWithChildren
  AuthRoute: typeof AuthRoute
  RepartoRepartoRoute: typeof RepartoRepartoRoute
  SchedaIdRoute: typeof SchedaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivio': {
      id: '/archivio'
      path: '/archivio'
      fullPath: '/archivio'
      preLoaderRoute: typeof ArchivioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivio/$ord': {
      id: '/archivio/$ord'
      path: '/$ord'
      fullPath: '/archivio/$ord'
      preLoaderRoute: typeof ArchivioOrdRouteImport
      parentRoute: typeof ArchivioRoute
    }
    '/reparto/$reparto': {
      id: '/reparto/$reparto'
      path: '/reparto/$reparto'
      fullPath: '/reparto/$reparto'
      preLoaderRoute: typeof RepartoRepartoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheda/$id': {
      id: '/scheda/$id'
      path: '/scheda/$id'
      fullPath: '/scheda/$id'
      preLoaderRoute: typeof SchedaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArchivioRouteChildren {
  ArchivioOrdRoute: typeof ArchivioOrdRoute
}

const ArchivioRouteChildren: ArchivioRouteChildren = {
  ArchivioOrdRoute: ArchivioOrdRoute,
}

const ArchivioRouteWithChildren = ArchivioRoute._addFileChildren(
  ArchivioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivioRoute: ArchivioRouteWithChildren,
  AuthRoute: AuthRoute,
  RepartoRepartoRoute: RepartoRepartoRoute,
  SchedaIdRoute: SchedaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
